### ISSUE TITLE
How to support RN 0.62.3?

### ISSUE THREAD

**Issue by owant** [nicastelo/react-native-swipeable-lists#3]
`import type {ListView} from 'react-native/Libraries/Lists/ListView/ListView';`
in source code `ListView` had remove in `react-native` and `import type {ListViewDataSource} from 'react-native/Libraries/Lists/ListView/ListViewDataSource';` is not supported

**Comment by nicastelo** [comment]
Hey, @owant

Thanks! I'll take a look later.
